apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels: 
    app: apache
    name: webserver
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: apache

  template:
    metadata:
      labels: 
        app: apache
    spec: 
      containers: 
        - name: myhttpd
          image: httpd
          ports: 
            - containerPort: 80