apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels: 
    app: apache
    name: webserver
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 8
  selector: 
    matchLabels:
      app: apache

  template:
    metadata:
      labels: 
        app: apache
    spec: 
      containers: 
        - name: myhttpd
          image: httpd
          ports: 
            - containerPort: 80
          volumeMounts: 
            - name: demovol
              mountPath: /data
      volumes: 
        - name: demovol
          hostPath:
            path: /data
            type: Directory